### ISSUE TITLE
Adding this package to a WebAPI project crashes application

### ISSUE THREAD

**Issue by dtjason** [petabridge/Petabridge.Tracing.ApplicationInsights#14]
Adding version 1.1 of this package to a brand new WebAPI (.Net 4.7.1) crashes the application.

Application shows a yellow error screen stating: Strong name signature could not be verified

Using 1.0 of the package works fine.

**Comment by Aaronontheweb** [comment]
Yeah, strong-naming issue... Let me see if we resolved that in a more recent release

**Comment by Aaronontheweb** [comment]
So this is where we added it: https://github.com/petabridge/Petabridge.Tracing.ApplicationInsights/pull/11

Can you share some details of your setup? I don't have this issue on any of our machines or CI systems when we use it.

**Comment by Aaronontheweb** [comment]
We removed strong naming so this should no longer be an issue.

**Comment by Aaronontheweb** [comment]
Well, looks like we never stopped strong-naming this - my mistake.

**Comment by Aaronontheweb** [comment]
https://github.com/petabridge/Petabridge.Tracing.ApplicationInsights/commit/9c38cb0b89b8dfd30dc8ac9a42248e2e32b598d7 <-- removed here, will release in a 0.4.0 distribution.
