### ISSUE TITLE
Could not load file or assembly 'Petabridge.Tracing.ApplicationInsights' Strong name signature could not be verified

### ISSUE THREAD

**Issue by sabbadino** [petabridge/Petabridge.Tracing.ApplicationInsights#84]
Petabridge.Tracing.ApplicationInsights, Version=0.2.1.0
Dotnetframework  v4.7.2 MVC project 

Could not load file or assembly 'Petabridge.Tracing.ApplicationInsights' or one of its dependencies. Strong name signature could not be verified.  The assembly may have been tampered with, or it was delay signed but not fully signed with the correct private key. (Exception from HRESULT: 0x80131045)

**Comment by Aaronontheweb** [comment]
We disabled strong naming for this package a couple of years ago: https://github.com/petabridge/Petabridge.Tracing.ApplicationInsights/issues/14

That might be why you're getting this error.
